name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/x86_64-unknown-linux-musl/release/beacon"
          token: ${{ secrets.GITHUB_TOKEN }}
